[0m20:48:36.122868 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8B6DED790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8B67AFC80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8B6D7FB00>]}


============================== 20:48:36.133998 | bf5bf167-1dba-4f94-bbe6-6df51fca958a ==============================
[0m20:48:36.133998 [info ] [MainThread]: Running with dbt=1.8.7
[0m20:48:36.135998 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Iheb\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt ', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:48:36.137712 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\Users\Iheb\Desktop\Cours\Projects\DeltaStore\deltastore_dbt_transformation\dbt_packages\dbt-utils-1.3.0\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:48:36.141122 [debug] [MainThread]: Command `cli deps` failed at 20:48:36.140787 after 1.38 seconds
[0m20:48:36.142123 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8B67AFC80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8B6EE7440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8B7906B10>]}
[0m20:48:36.143124 [debug] [MainThread]: Flushing usage events
[0m20:48:40.275164 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019FE9F858B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019FE90F1370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019FE6EC1A90>]}


============================== 20:48:40.292663 | 857cfd7b-3543-495d-aea6-38de645dc489 ==============================
[0m20:48:40.292663 [info ] [MainThread]: Running with dbt=1.8.7
[0m20:48:40.294666 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Iheb\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt ', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:48:40.296375 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\Users\Iheb\Desktop\Cours\Projects\DeltaStore\deltastore_dbt_transformation\dbt_packages\dbt-utils-1.3.0\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:48:40.298892 [debug] [MainThread]: Command `cli deps` failed at 20:48:40.298892 after 0.38 seconds
[0m20:48:40.299891 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019FE9C361E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019FE9F1EA50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019FE9F1EBA0>]}
[0m20:48:40.300892 [debug] [MainThread]: Flushing usage events
